"""empty message

Revision ID: 3752bc8e3dac
Revises: f660a3ee52ba
Create Date: 2019-02-19 21:08:21.689200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3752bc8e3dac'
down_revision = 'f660a3ee52ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=300), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
