"""empty message

Revision ID: 8c1c6117b29a
Revises: dbf96aa5339d
Create Date: 2019-02-19 20:27:56.194378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c1c6117b29a'
down_revision = 'dbf96aa5339d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hash_pass', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hash_pass')
    # ### end Alembic commands ###
