"""empty message

Revision ID: bd0ddd02bad0
Revises: 3752bc8e3dac
Create Date: 2019-02-21 10:26:51.234174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd0ddd02bad0'
down_revision = '3752bc8e3dac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
