"""empty message

Revision ID: f660a3ee52ba
Revises: 8c1c6117b29a
Create Date: 2019-02-19 20:59:30.207521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f660a3ee52ba'
down_revision = '8c1c6117b29a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.String(length=250), nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.String(length=250), nullable=True))
    op.drop_column('users', 'hash_pass')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hash_pass', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###
